services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION="eu-west-1"
      - AWS_ACCESS_KEY_ID="eu-west-1"
      - AWS_SECRET_ACCESS_KEY="eu-west-1"
